name: robot-name
version: 0.1.0.4

# Global dependencies can be specified here, but it's often clearer
# to list them per-component (library, executable, test).
# dependencies:
#   - base

library:
  exposed-modules: Robot
  source-dirs: src
  ghc-options: -Wall
  dependencies: # Explicitly list library dependencies here
    - base
    - mtl
    - random
    - containers
    - stm

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - robot-name # Depends on the library itself
      - hspec      # Test framework dependency
      # Add other test-specific dependencies here if needed

