name: grade-school
version: 1.0.0.4

dependencies:
  - base >= 4.12 && < 5

library:
  exposed-modules: School
  source-dirs: src
  ghc-options: -Wall

tests:
  test:
    main: Tests.hs
    source-dirs: test
    ghc-options: -Wall
    dependencies:
      - grade-school
      - hspec
