name: wordy
version: 1.5.0.8

dependencies:
  - base >= 4.7 && < 5
  - parsec

library:
  exposed-modules: WordProblem
  source-dirs: src
  ghc-options: -Wall
  dependencies:
    - parsec

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - wordy
      - hspec
      - parsec
