name: bank-account
version: 0.1.0.4

dependencies:
  - base
  - stm        # Added stm dependency

library:
  exposed-modules: BankAccount
  source-dirs: src
  ghc-options: -Wall
  dependencies:
   - stm       # Added stm dependency here too for clarity/completeness

tests:
  test:
    main: Tests.hs
    source-dirs: test
    ghc-options: -threaded -rtsopts -with-rtsopts=-N
    dependencies:
      - bank-account
      - hspec
