name: simple-cipher
version: 1.2.0.5

# Common settings -------------------------------------------------------------
# In an hpack (package.yaml) file the top-level `dependencies` field does **not**
# propagate into individual components.  Each component needs its own stanza.
# That is why GHC could not find the `random` package when compiling the
# library.  We move the dependency list into the `library` stanza so that the
# Cipher module sees it.

library:
  exposed-modules: Cipher
  source-dirs: src
  ghc-options: -Wall
  dependencies:
    - base
    - random        # required for caesarEncodeRandom

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - simple-cipher
      - hspec
      - random
