name: two-bucket
version: 1.0.0.0

# Explicitly list the dependencies for every component so that Cabal can
# correctly expose the needed libraries during compilation.
library:
  exposed-modules:
    - TwoBucket
  source-dirs: src
  ghc-options: -Wall
  dependencies:
    - base
    - containers
    - mtl

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - two-bucket
      - hspec
