name: bank-account
version: 0.1.0.4

dependencies:
  - base
  # stm was removed from here as it's specified in library.dependencies

library:
  exposed-modules: BankAccount
  source-dirs: src
  ghc-options: -Wall
  dependencies:
   - stm # stm is correctly listed here for the library

tests:
  test:
    main: Tests.hs
    source-dirs: test
    ghc-options: -threaded -rtsopts -with-rtsopts=-N
    dependencies:
      - bank-account
      - hspec
