name: hexadecimal
version: 0.1.0.3

dependencies:
  - base >= 4.7 && < 5

library:
  exposed-modules: Hexadecimal
  source-dirs: src
  ghc-options: -Wall

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - hexadecimal
      - hspec
