name: secret-handshake
version: 1.2.0.6

dependencies:
  - base

library:
  exposed-modules: SecretHandshake
  source-dirs: src
  ghc-options: -Wall
  dependencies:
    - base

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - secret-handshake
      - hspec
