name: forth
version: 1.7.1.13

dependencies:
  - base
  - text
  # Removed containers from global dependencies

library:
  exposed-modules: Forth
  source-dirs: src
  ghc-options: -Wall
  dependencies: # Added library-specific dependencies section
   - containers # Added containers here

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - forth
      - hspec
