name: satellite
version: 1.0.0.0

dependencies:
  - base

library:
  exposed-modules:
  - Satellite
  - BinaryTree
  source-dirs: src
  ghc-options: -Wall

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - satellite
      - hspec
