name: knapsack
version: 1.0.0.0

dependencies:
  - base
  - array # Add the array package dependency here

library:
  exposed-modules: Knapsack
  source-dirs: src
  ghc-options: -Wall
  # dependencies: # Dependencies can also be listed here per-component
  # - foo       # List here the packages you
  # - bar       # want to use in your solution.

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - knapsack
      - hspec
