name: grade-school
version: 1.0.0.4

dependencies:
  - base
  - containers # Global dependency, available to all components

library:
  exposed-modules: School
  source-dirs: src
  ghc-options: -Wall
  dependencies:
    # Explicitly list dependencies for the library.
    # This ensures 'base' and 'containers' are definitely included
    # when Hpack generates the .cabal file from this package.yaml.
    - base
    - containers

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - grade-school # This depends on the library, which will have 'containers'
      - hspec
