name: rail-fence-cipher
version: 0.1.0.0
github: "githubuser/rail-fence-cipher"
license: MIT
author: "Author name here"
maintainer: "author@example.com"
copyright: "2023 Author name here"

extra-source-files:
  - README.md
  - CHANGELOG.md

# Metadata used when publishing your package
# synopsis: A short synopsis of your package
# category: Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/githubuser/rail-fence-cipher#readme>

dependencies:
  - base >= 4.7 && < 5
  - containers # For Data.Map or Data.Set if needed, though not strictly used in current solution
  - array # For Data.Array if needed

library:
  source-dirs: src
  exposed-modules:
    - RailFenceCipher

tests:
  rail-fence-cipher-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - rail-fence-cipher
      - hspec
