name: spiral-matrix
version: 1.1.0.3

# Component settings ----------------------------------------------------------

library:
  exposed-modules: Spiral
  source-dirs: src
  ghc-options: -Wall
  dependencies:
    - base   >= 4.7 && < 5
    - array  >= 0.5 && < 0.6

tests:
  test:
    main:        Tests.hs
    source-dirs: test
    dependencies:
      - spiral-matrix
      - base   >= 4.7 && < 5
      - array  >= 0.5 && < 0.6
      - hspec
