name: connect
version: 1.1.0.6

library:
  source-dirs: src
  exposed-modules: Connect
  ghc-options: -Wall
  dependencies:
    - base
    - containers        # for Data.Set

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - connect
      - hspec
