name: change
version: 1.3.0.7

dependencies:
  - base          # Prelude and core libraries
  - array         # Needed for Data.Array used in src/Change.hs

library:
  exposed-modules: Change
  source-dirs: src
  ghc-options: -Wall

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - change
      - hspec
