name: spiral-matrix
version: 1.1.0.3

# Packages that the library (and, transitively, the test‑suite) depends on.
dependencies:
  - base
  - array     # ← needed for Data.Array used in Spiral.hs

library:
  exposed-modules: Spiral
  source-dirs: src
  ghc-options: -Wall

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - spiral-matrix
      - hspec
