name: reverse-string
version: 0.1.0.0

dependencies:
  - base

library:
  exposed-modules: ReverseString
  source-dirs: src
  ghc-options: -Wall

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - reverse-string
      - hspec
