name: simple-cipher
version: 1.2.0.5

dependencies:
  - base
  - random          # <‑‑ добавили random

library:
  exposed-modules: Cipher
  source-dirs: src
  ghc-options: -Wall
  # при необходимости можно добавить и здесь:
  # dependencies:
  #   - random

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - simple-cipher
      - hspec
