name: grade-school
version: 1.0.0.4

dependencies:
  - base
  # Note: While adding dependencies here is possible, it's generally better
  # to specify them per-component (library, executable, test) below.
  # Dependencies listed here are inherited by all components unless overridden.

library:
  exposed-modules: School
  source-dirs: src
  ghc-options: -Wall
  dependencies:
   - containers # Added dependency for the library component

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - grade-school
      - hspec
      - containers # Tests might also need access depending on how they are written, though likely inherited via grade-school
