name: dominoes
version: 2.1.0.9

dependencies:
  - base
  - containers          # Data.Map and Data.Set live in this package

library:
  exposed-modules: Dominoes
  source-dirs: src
  ghc-options: -Wall

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - dominoes
      - hspec
      - containers      # ensure the test component also sees the package
