name: sgf-parsing
version: 1.2.0.5

library:
  exposed-modules: Sgf
  source-dirs: src
  ghc-options: -Wall
  dependencies:
    - base >= 4.14 && < 5
    - containers
    - text
    - parsec

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - sgf-parsing
      - hspec
