name: simple-cipher
version: 1.2.0.5

library:
  exposed-modules: Cipher
  source-dirs: src
  ghc-options: -Wall
  dependencies:
    - base
    - random

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - simple-cipher
      - hspec
      - random
