name: bank-account
version: 0.1.0.4

dependencies:
  - base
  - stm

library:
  exposed-modules: BankAccount
  source-dirs: src
  ghc-options: -Wall
  dependencies:
  - stm       # Added stm to library dependencies

tests:
  test:
    main: Tests.hs
    source-dirs: test
    ghc-options: -threaded -rtsopts -with-rtsopts=-N
    dependencies:
      - bank-account
      - hspec
